jobs:
- title: Creative Content Writer
  date: Oct 4, 2017
  url: creative-content-writer
- title: Digital Marketing Manager
  date: Sep 19, 2017
  url: digital-marketing-manager
- title: ReactJS Front-end Developer
  date: Aug 23, 2017
  url: react-js-front-end-developer
- title: UI/UX Designer
  date: Aug 23, 2017
  url: ui-ux-designer